# Generated by Django 2.2.6 on 2019-11-05 21:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='MeterRead',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('read_month', models.CharField(blank=True, max_length=64)),
                ('city_gate_dekatherm', models.FloatField()),
                ('burner_tip_dekatherm', models.FloatField()),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('design_day_mcf', models.FloatField(blank=True, null=True)),
                ('design_day_dekatherm', models.FloatField(blank=True, null=True)),
                ('read_source', models.CharField(blank=True, max_length=64)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('object_id', models.PositiveIntegerField()),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType')),
            ],
            options={
                'ordering': ['start_date'],
            },
        ),
    ]
