# Generated by Django 2.2.6 on 2019-11-05 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Meter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meter', models.CharField(max_length=64)),
                ('gas_south_account_number', models.CharField(max_length=64)),
                ('ldc_account_number', models.CharField(blank=True, max_length=64, verbose_name='LDC account number')),
                ('premise_number', models.CharField(blank=True, max_length=64)),
                ('location', models.CharField(choices=[('ATL', 'ATL'), ('Ex-SNG', 'Ex-SNG'), ('BRU', 'BRU'), ('ROM', 'ROM'), ('AUG', 'AUG'), ('SAV', 'SAV'), ('MAC', 'MAC'), ('VAL', 'VAL'), ('Ex-Transco', 'Ex-Transco')], default='ATL', max_length=20)),
                ('county', models.CharField(blank=True, max_length=64)),
                ('record_type', models.CharField(blank=True, max_length=64)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
